# Generated by Django 4.2.7 on 2023-11-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Becedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj_name', models.CharField(max_length=200)),
                ('subj_type', models.CharField(max_length=200)),
                ('subj_grade', models.IntegerField()),
                ('subj_add', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
